LANG_TEXT = {'en_EN': {'tr_TR': 'Turkish',
           'fr_FR': 'French',
           'fi_FI': 'Finnish',
           'pt_PT': 'Portuguese',
           'fy_x-FY': 'Frisian',
           'it_IT': 'Italian',
           'et_EE': 'Estonian',
           'no_NO': 'Norwegian',
           'nl_NL': 'Dutch',
           'lv_LV': 'Latvian',
           'el_GR': 'Greek',
           'pt_BR_BR': 'Brazilian Portuguese',
           'hu_HU': 'Hungarian',
           'lt_LT': 'Lithuanian',
           'sl_SI': 'Slovenian',
           'hr_HR': 'Croatian',
           'en_EN': 'English',
           'es_ES': 'Spanish',
           'ca_AD': 'Catalan',
           'ru_RU': 'Russian',
           'is_IS': 'Icelandic',
           'da_DK': 'Danish',
           'ar_AE': 'Arabic',
           'sk_SK': 'Slovakian',
           'de_DE': 'German',
           'sr_YU': 'Serbian',
           'cs_CZ': 'Czech',
           'pl_PL': 'Polish',
           'uk_UA': 'Ukrainian',
           'fa_IR': 'Persian',
           'sv_SE': 'Swedish',
           'he_IL': 'Hebrew',
           'T1': 'Please use the UP and DOWN keys to select your language. Afterwards press the OK button.',
           'T2': 'Language selection'},
 'de_DE': {'tr_TR': 'T\xc3\xbcrkisch',
           'fr_FR': 'Franz\xc3\xb6sisch',
           'fi_FI': 'Finnisch',
           'pt_PT': 'portugiesisch',
           'fy_x-FY': 'Friesisch',
           'it_IT': 'Italienisch',
           'et_EE': 'Estnisch',
           'no_NO': 'Norwegisch',
           'nl_NL': 'Holl\xc3\xa4ndisch',
           'lv_LV': 'Lettisch',
           'el_GR': 'Griechisch',
           'pt_BR_BR': 'Brazilian Portuguese',
           'hu_HU': 'Ungarisch',
           'lt_LT': 'litauisch',
           'sl_SI': 'Slowenisch',
           'hr_HR': 'Kroatisch',
           'en_EN': 'Englisch',
           'es_ES': 'Spanisch',
           'ca_AD': 'Katalanisch',
           'ru_RU': 'Russisch',
           'is_IS': 'Isl\xc3\xa4ndisch',
           'da_DK': 'D\xc3\xa4nisch',
           'ar_AE': 'Arabisch',
           'sk_SK': 'Slowakisch',
           'de_DE': 'Deutsch',
           'sr_YU': 'Serbisch',
           'cs_CZ': 'Tschechisch',
           'pl_PL': 'Polnisch',
           'uk_UA': 'Ukrainisch',
           'fa_IR': 'Persisch',
           'sv_SE': 'Schwedisch',
           'he_IL': 'Hebr\xc3\xa4isch',
           'T1': 'Bitte benutzen Sie die Hoch/Runter-Tasten, um Ihre Sprache auszuw\xc3\xa4hlen. Danach dr\xc3\xbccken Sie bitte OK.',
           'T2': 'Sprachauswahl'},
 'ar_AE': {'tr_TR': '\xd8\xaa\xd8\xb1\xd9\x83\xd9\x89',
           'fr_FR': '\xd9\x81\xd8\xb1\xd9\x86\xd8\xb3\xd9\x89',
           'fi_FI': '\xd8\xa5\xd9\x86\xd8\xaa\xd9\x87\xd8\xa7\xd8\xa1',
           'pt_PT': '\xd8\xa8\xd8\xb1\xd8\xaa\xd8\xba\xd8\xa7\xd9\x84\xd9\x89',
           'fy_x-FY': 'Frisian',
           'it_IT': '\xd8\xa5\xd9\x8a\xd8\xb7\xd8\xa7\xd9\x84\xd9\x89',
           'et_EE': '\xd8\xa3\xd8\xb3\xd8\xaa\xd9\x88\xd9\x86\xd9\x89',
           'no_NO': '\xd9\x86\xd8\xb1\xd9\x88\xd9\x8a\xd8\xac\xd9\x89',
           'nl_NL': '\xd9\x87\xd9\x88\xd9\x84\xd9\x86\xd8\xaf\xd9\x89',
           'lv_LV': 'Latvian',
           'el_GR': '\xd8\xa7\xd9\x84\xd9\x8a\xd9\x88\xd9\x86\xd8\xa7\xd9\x86',
           'pt_BR_BR': 'Brazilian Portuguese',
           'hu_HU': '\xd9\x85\xd8\xac\xd8\xb1\xd9\x89',
           'lt_LT': '\xd9\x84\xd9\x8a\xd8\xaa\xd9\x88\xd8\xa7\xd9\x86\xd9\x89',
           'sl_SI': '\xd8\xb3\xd9\x84\xd9\x88\xd9\x81\xd8\xa7\xd9\x86\xd9\x89',
           'hr_HR': '\xd9\x83\xd8\xb1\xd9\x88\xd8\xa7\xd8\xaa\xd9\x89',
           'en_EN': '\xd8\xa5\xd9\x86\xd8\xac\xd9\x84\xd9\x8a\xd8\xb2\xd9\x89',
           'es_ES': '\xd8\xa3\xd8\xb3\xd8\xa8\xd8\xa7\xd9\x86\xd9\x89',
           'ca_AD': '\xd9\x83\xd8\xa7\xd8\xaa\xd8\xa7\xd9\x84\xd8\xa7\xd9\x86\xd9\x8a',
           'ru_RU': '\xd8\xb1\xd9\x88\xd8\xb3\xd9\x89',
           'is_IS': '\xd8\xa7\xd9\x8a\xd8\xb3\xd9\x84\xd9\x86\xd8\xaf\xd9\x89',
           'da_DK': '\xd8\xaf\xd9\x86\xd9\x85\xd8\xa7\xd8\xb1\xd9\x83\xd9\x89',
           'ar_AE': '\xd8\xb9\xd9\x80\xd8\xb1\xd8\xa8\xd9\x89',
           'sk_SK': '\xd8\xb3\xd9\x84\xd9\x88\xd9\x81\xd8\xa7\xd9\x83\xd9\x89',
           'de_DE': '\xd8\xa7\xd9\x84\xd9\x85\xd8\xa7\xd9\x86\xd9\x80\xd9\x89',
           'sr_YU': '\xd8\xb5\xd8\xb1\xd9\x8a\xd9\x89',
           'cs_CZ': '\xd8\xa7\xd9\x84\xd8\xaa\xd8\xb4\xd9\x8a\xd9\x83',
           'pl_PL': '\xd8\xa8\xd9\x88\xd9\x84\xd9\x86\xd8\xaf\xd9\x89',
           'uk_UA': '\xd8\xa3\xd9\x88\xd9\x83\xd8\xb1\xd8\xa7\xd9\x86\xd9\x89',
           'fa_IR': 'Persian',
           'sv_SE': '\xd8\xb3\xd9\x88\xd9\x8a\xd8\xaf\xd9\x89',
           'he_IL': 'Hebrew',
           'T1': '\xd9\x85\xd9\x86 \xd9\x81\xd8\xb6\xd9\x84\xd9\x83 \xd8\xa3\xd8\xb3\xd8\xaa\xd8\xae\xd8\xaf\xd9\x85 \xd8\xb0\xd8\xb1 \xd8\xa7\xd9\x84\xd8\xb3\xd9\x87\xd9\x85 \xd8\xa7\xd9\x84\xd8\xb9\xd9\x84\xd9\x88\xd9\x89 \xd8\xa3\xd9\x88 \xd8\xa7\xd9\x84\xd8\xb3\xd9\x81\xd9\x84\xd9\x89 \xd9\x84\xd8\xa5\xd8\xae\xd8\xaa\xd9\x8a\xd8\xa7\xd8\xb1 \xd8\xa7\xd9\x84\xd9\x84\xd8\xba\xd9\x87. \xd8\xab\xd9\x85 \xd8\xa3\xd8\xb6\xd8\xba\xd8\xb7 \xd9\x85\xd9\x88\xd8\xa7\xd9\x81\xd9\x82 .',
           'T2': '\xd8\xa5\xd8\xae\xd8\xaa\xd9\x8a\xd8\xa7\xd8\xb1 \xd8\xa7\xd9\x84\xd9\x84\xd8\xba\xd9\x80\xd9\x87'},
 'pt_BR_BR': {'tr_TR': 'Turco',
              'fr_FR': 'Franc\xc3\xaas',
              'fi_FI': 'Finland\xc3\xaas',
              'pt_PT': 'Portugu\xc3\xaas brasileiro',
              'fy_x-FY': 'Fr\xc3\xadsio',
              'it_IT': 'Italiano',
              'et_EE': 'Estoniano',
              'no_NO': 'Noruegu\xc3\xaas',
              'nl_NL': 'Holand\xc3\xaas',
              'lv_LV': 'Let\xc3\xa3o',
              'el_GR': 'Grego',
              'pt_BR_BR': 'Brazilian Portuguese',
              'hu_HU': 'H\xc3\xbangaro',
              'lt_LT': 'Lituano',
              'sl_SI': 'Esloveno',
              'hr_HR': 'Croata',
              'en_EN': 'Ingl\xc3\xaas',
              'es_ES': 'Catal\xc3\xa3o',
              'ca_AD': 'Catal\xc3\xa3o',
              'ru_RU': 'Russo',
              'is_IS': 'Island\xc3\xaas',
              'da_DK': 'Dinamarqu\xc3\xaas',
              'ar_AE': '\xc3\x81rabe',
              'sk_SK': 'Eslovaco',
              'de_DE': 'Alem\xc3\xa3o',
              'sr_YU': 'S\xc3\xa9rvia',
              'cs_CZ': 'Checo',
              'pl_PL': 'Polaco',
              'uk_UA': 'Ucraniano',
              'fa_IR': 'Persa',
              'sv_SE': 'Sueco',
              'he_IL': 'Hebr\xc3\xa1ico',
              'T1': 'Use a tecla de cima ou de baixo para selecionar seu idioma. Depois pressione OK.',
              'T2': 'Sele\xc3\xa7\xc3\xa3o do idioma'},
 'ca_AD': {'tr_TR': 'Turc',
           'fr_FR': 'Franc\xc3\xa8s',
           'fi_FI': 'Finland\xc3\xa8s',
           'pt_PT': 'Portugu\xc3\xa8s',
           'fy_x-FY': 'Frisian',
           'it_IT': 'Itali\xc3\xa0',
           'et_EE': 'Estonian',
           'no_NO': 'Noruec',
           'nl_NL': 'Holand\xc3\xa8s',
           'lv_LV': 'Latvian',
           'el_GR': 'Grec',
           'pt_BR_BR': 'Brazilian Portuguese',
           'hu_HU': 'Hongar\xc3\xa8s',
           'lt_LT': 'Litu\xc3\xa0',
           'sl_SI': 'Slovenian',
           'hr_HR': 'Croat',
           'en_EN': 'Angl\xc3\xa8s',
           'es_ES': 'Espanyol',
           'ca_AD': 'Catal\xc3\xa0',
           'ru_RU': 'Rus',
           'is_IS': 'Island\xc3\xa8s',
           'da_DK': 'Dan\xc3\xa8s',
           'ar_AE': '\xc3\x80rab',
           'sk_SK': 'Slovakian',
           'de_DE': 'Alemany',
           'sr_YU': 'Serbian',
           'cs_CZ': 'Txec',
           'pl_PL': 'Polish',
           'uk_UA': 'Ukrainian',
           'fa_IR': 'Persian',
           'sv_SE': 'Suec',
           'he_IL': 'Hebrew',
           'T1': 'Please use the UP and DOWN keys to select your language. Afterwards press the OK button.',
           'T2': "Selecci\xc3\xb3 d'idioma"},
 'hr_HR': {'tr_TR': 'Turski',
           'fr_FR': 'Francuski',
           'fi_FI': 'Finski',
           'pt_PT': 'Portugalski',
           'fy_x-FY': 'Frisian',
           'it_IT': 'Talijanski',
           'et_EE': 'Estonian',
           'no_NO': 'Norve\xc5\xa1ki',
           'nl_NL': 'Nizozemski',
           'lv_LV': 'Latvian',
           'el_GR': 'Gr\xc4\x8dki',
           'pt_BR_BR': 'Brazilian Portuguese',
           'hu_HU': 'Ma\xc4\x91arski',
           'lt_LT': 'Litvanski',
           'sl_SI': 'Slovenian',
           'hr_HR': 'Hrvatski',
           'en_EN': 'Engleski',
           'es_ES': '\xc5\xa0panjolski',
           'ca_AD': 'Katalonski',
           'ru_RU': 'Ruski',
           'is_IS': 'Islandski',
           'da_DK': 'Danski',
           'ar_AE': 'Arabski',
           'sk_SK': 'Slovakian',
           'de_DE': 'Njema\xc4\x8dki',
           'sr_YU': 'Serbian',
           'cs_CZ': '\xc4\x8ce\xc5\xa1ki',
           'pl_PL': 'Poljski',
           'uk_UA': 'Ukrainian',
           'fa_IR': 'Persian',
           'sv_SE': '\xc5\xa0vedski',
           'he_IL': 'Hebrew',
           'T1': 'Please use the UP and DOWN keys to select your language. Afterwards press the OK button.',
           'T2': 'Odaberite Jezik'},
 'cs_CZ': {'tr_TR': 'Turecky',
           'fr_FR': 'Francouzsky',
           'fi_FI': 'Finsky',
           'pt_PT': 'Portugalsky',
           'fy_x-FY': 'Frisian',
           'it_IT': 'Italsky',
           'et_EE': 'Estonian',
           'no_NO': 'Norsky',
           'nl_NL': 'Holandsky',
           'lv_LV': 'Latvian',
           'el_GR': '\xc5\x98ecky',
           'pt_BR_BR': 'Brazilian Portuguese',
           'hu_HU': 'Ma\xc4\x8farsky',
           'lt_LT': 'Litevsky',
           'sl_SI': 'Slovenian',
           'hr_HR': 'Chorvatsky',
           'en_EN': 'Anglicky',
           'es_ES': '\xc5\xa0pan\xc4\x9blsky',
           'ca_AD': 'Katal\xc3\xa1nsky',
           'ru_RU': 'Rusky',
           'is_IS': 'Islandsky',
           'da_DK': 'D\xc3\xa1nsky',
           'ar_AE': 'Arabsky',
           'sk_SK': 'Slovakian',
           'de_DE': 'N\xc4\x9bmecky',
           'sr_YU': 'Serbian',
           'cs_CZ': '\xc4\x8cesky',
           'pl_PL': 'Polsky',
           'uk_UA': 'Ukrainian',
           'fa_IR': 'Persian',
           'sv_SE': '\xc5\xa0v\xc3\xa9dsky',
           'he_IL': 'Hebrew',
           'T1': 'Please use the UP and DOWN keys to select your language. Afterwards press the OK button.',
           'T2': 'V\xc3\xbdb\xc4\x9br jazyka'},
 'da_DK': {'tr_TR': 'Tyrkisk',
           'fr_FR': 'Fransk',
           'fi_FI': 'Finsk',
           'pt_PT': 'Portugisisk',
           'fy_x-FY': 'Frisisk',
           'it_IT': 'Italiensk',
           'et_EE': 'Estisk',
           'no_NO': 'Norsk',
           'nl_NL': 'Hollandsk',
           'lv_LV': 'Lettisk',
           'el_GR': 'Gr\xc3\xa6sk',
           'pt_BR_BR': 'Brazilian Portuguese',
           'hu_HU': 'Ungarsk',
           'lt_LT': 'Litauisk',
           'sl_SI': 'Slovensk',
           'hr_HR': 'Kroatisk',
           'en_EN': 'Engelsk',
           'es_ES': 'Spansk',
           'ca_AD': 'Katalansk',
           'ru_RU': 'Russisk',
           'is_IS': 'Islandsk',
           'da_DK': 'Dansk',
           'ar_AE': 'Arabisk',
           'sk_SK': 'Slovakisk',
           'de_DE': 'Tysk',
           'sr_YU': 'Serbisk',
           'cs_CZ': 'Tjekkisk',
           'pl_PL': 'Polsk',
           'uk_UA': 'Ukrainsk',
           'fa_IR': 'Persisk',
           'sv_SE': 'Svensk',
           'he_IL': 'Hebr\xc3\xa6isk',
           'T1': 'Benyt venligst OP og NED tasten til at v\xc3\xa6lge sprog. Tryk bagefter p\xc3\xa5 OK knappen.',
           'T2': 'Valg af sprog'},
 'nl_NL': {'tr_TR': 'Turks',
           'fr_FR': 'Frans',
           'fi_FI': 'Fins',
           'pt_PT': 'Portugees',
           'fy_x-FY': 'Fries',
           'it_IT': 'Italiaans',
           'et_EE': 'Estlands',
           'no_NO': 'Noors',
           'nl_NL': 'Nederlands',
           'lv_LV': 'Lets',
           'el_GR': 'Grieks',
           'pt_BR_BR': 'Brazilian Portuguese',
           'hu_HU': 'Hongaars',
           'lt_LT': 'Litouws',
           'sl_SI': 'Sloveens',
           'hr_HR': 'Kroatisch',
           'en_EN': 'Engels',
           'es_ES': 'Spaans',
           'ca_AD': 'Catalaans',
           'ru_RU': 'Russisch',
           'is_IS': 'Ijslands',
           'da_DK': 'Deens',
           'ar_AE': 'Arabisch',
           'sk_SK': 'Slowaaks',
           'de_DE': 'Duits',
           'sr_YU': 'Servisch',
           'cs_CZ': 'Tsjechisch',
           'pl_PL': 'Pools',
           'uk_UA': 'Oekra\xc3\xafens',
           'fa_IR': 'Perzisch',
           'sv_SE': 'Zweeds',
           'he_IL': 'Hebreeuws',
           'T1': 'Gebruik de omhoog/omlaag toeten om de gewenste taal te selecteren. Druk daarna op OK.',
           'T2': 'Taalkeuze'},
 'et_EE': {'tr_TR': 'T\xc3\xbcrgi',
           'fr_FR': 'Prantsuse',
           'fi_FI': 'Soome',
           'pt_PT': 'Portugali',
           'fy_x-FY': 'Friisi',
           'it_IT': 'Itaalia',
           'et_EE': 'Eesti',
           'no_NO': 'Norra',
           'nl_NL': 'Holland',
           'lv_LV': 'L\xc3\xa4ti',
           'el_GR': 'Kreeka',
           'pt_BR_BR': 'Brazilian Portuguese',
           'hu_HU': 'Ungari',
           'lt_LT': 'Leedu',
           'sl_SI': 'Sloveenia',
           'hr_HR': 'Horvaatia',
           'en_EN': 'Inglise',
           'es_ES': 'Hispaania',
           'ca_AD': 'Katalaani',
           'ru_RU': 'Vene',
           'is_IS': 'Island',
           'da_DK': 'Taani',
           'ar_AE': 'Araabia',
           'sk_SK': 'Slovakkia',
           'de_DE': 'Saksa',
           'sr_YU': 'Serbia',
           'cs_CZ': 'T\xc5\xa1ehhi',
           'pl_PL': 'Poola',
           'uk_UA': 'Ukraina',
           'fa_IR': 'P\xc3\xa4rsia',
           'sv_SE': 'Rootsi',
           'he_IL': 'Hebrew',
           'T1': 'Palun kasuta UP ja DOWN nuppe oma keele valimiseks.Keele valimiseks vajuta OK.',
           'T2': 'Keele valik'},
 'fi_FI': {'tr_TR': 'Turkki',
           'fr_FR': 'Ranska',
           'fi_FI': 'Suomi',
           'pt_PT': 'Portugali',
           'fy_x-FY': 'Friisi',
           'it_IT': 'Italia',
           'et_EE': 'Viro',
           'no_NO': 'Norja',
           'nl_NL': 'Hollanti',
           'lv_LV': 'Latvia',
           'el_GR': 'Kreikka',
           'pt_BR_BR': 'Brazilian Portuguese',
           'hu_HU': 'Unkari',
           'lt_LT': 'Liettua',
           'sl_SI': 'Slovenia',
           'hr_HR': 'Kroatia',
           'en_EN': 'Englanti',
           'es_ES': 'Espanja',
           'ca_AD': 'Katalaani',
           'ru_RU': 'Ven\xc3\xa4j\xc3\xa4',
           'is_IS': 'Islanti',
           'da_DK': 'Tanska',
           'ar_AE': 'Arabia',
           'sk_SK': 'Slovakia',
           'de_DE': 'Saksa',
           'sr_YU': 'Serbia',
           'cs_CZ': 'T\xc5\xa1ekki',
           'pl_PL': 'Puola',
           'uk_UA': 'Ukraina',
           'fa_IR': 'Persia',
           'sv_SE': 'Ruotsi',
           'he_IL': 'Hebrea',
           'T1': 'Valitse kieli yl\xc3\xb6s/alas n\xc3\xa4pp\xc3\xa4imill\xc3\xa4 ja paina OK-n\xc3\xa4pp\xc3\xa4int\xc3\xa4.',
           'T2': 'Kielivalinta'},
 'fr_FR': {'tr_TR': 'Turke',
           'fr_FR': 'Fran\xc3\xa7ais',
           'fi_FI': 'Finlandais',
           'pt_PT': 'Portugais',
           'fy_x-FY': 'Frison',
           'it_IT': 'Italien',
           'et_EE': 'Estonien',
           'no_NO': 'Norv\xc3\xa9gien',
           'nl_NL': 'Hollandais',
           'lv_LV': 'Letton',
           'el_GR': 'Gr\xc3\xa8que',
           'pt_BR_BR': 'Brazilian Portuguese',
           'hu_HU': 'Hongrois',
           'lt_LT': 'Lithuanien',
           'sl_SI': 'Slov\xc3\xa8ne',
           'hr_HR': 'Croate',
           'en_EN': 'Anglais',
           'es_ES': 'Espagnol',
           'ca_AD': 'Catalan',
           'ru_RU': 'Russe',
           'is_IS': 'Islandais',
           'da_DK': 'Danois',
           'ar_AE': 'Arabe',
           'sk_SK': 'Slovaque',
           'de_DE': 'Allemand',
           'sr_YU': 'Serbe',
           'cs_CZ': 'Tch\xc3\xa8que',
           'pl_PL': 'Polonais',
           'uk_UA': 'Ukrainien',
           'fa_IR': 'Iranien',
           'sv_SE': 'Su\xc3\xa9dois',
           'he_IL': 'Hebrew',
           'T1': 'Veuillez utiliser les touches HAUT et BAS pour choisir votre langage. Ensuite presser le bouton OK.',
           'T2': 'S\xc3\xa9lection de la langue'},
 'el_GR': {'tr_TR': '\xce\xa4\xce\xbf\xcf\x8d\xcf\x81\xce\xba\xce\xb9\xce\xba\xce\xb1',
           'fr_FR': '\xce\x93\xce\xb1\xce\xbb\xce\xbb\xce\xb9\xce\xba\xce\xac',
           'fi_FI': '\xce\xa6\xce\xb9\xce\xbb\xce\xbb\xce\xb1\xce\xbd\xce\xb4\xce\xb9\xce\xba\xce\xac',
           'pt_PT': '\xce\xa0\xce\xbf\xcf\x81\xcf\x84\xce\xbf\xce\xb3\xce\xb1\xce\xbb\xce\xbb\xce\xb9\xce\xba\xce\xac',
           'fy_x-FY': 'Frisian',
           'it_IT': '\xce\x99\xcf\x84\xce\xb1\xce\xbb\xce\xb9\xce\xba\xce\xac',
           'et_EE': 'Estonian',
           'no_NO': '\xce\x9d\xce\xbf\xcf\x81\xce\xb2\xce\xb7\xcf\x86\xce\xb9\xce\xba\xce\xac',
           'nl_NL': '\xce\x9f\xce\xbb\xce\xbb\xce\xb1\xce\xbd\xce\xb4\xce\xb9\xce\xba\xce\xac',
           'lv_LV': 'Latvian',
           'el_GR': '\xce\x95\xce\xbb\xce\xbb\xce\xb7\xce\xbd\xce\xb9\xce\xba\xce\xac',
           'pt_BR_BR': 'Brazilian Portuguese',
           'hu_HU': '\xce\x9f\xcf\x85\xce\xb3\xce\xb3\xce\xb1\xcf\x81\xce\xb5\xce\xb6\xce\xb9\xce\xba\xce\xac',
           'lt_LT': '\xce\x9b\xce\xb9\xce\xb8\xce\xbf\xcf\x85\xce\xb1\xce\xbd\xce\xb9\xce\xba\xce\xac',
           'sl_SI': 'Slovenian',
           'hr_HR': '\xce\x9a\xcf\x81\xce\xbf\xce\xac\xcf\x84\xce\xb9\xce\xba\xce\xb1',
           'en_EN': '\xce\x91\xce\xb3\xce\xb3\xce\xbb\xce\xb9\xce\xba\xce\xac',
           'es_ES': '\xce\x99\xcf\x83\xcf\x80\xce\xb1\xce\xbd\xce\xb9\xce\xba\xce\xac',
           'ca_AD': 'Catalan',
           'ru_RU': '\xce\xa1\xcf\x89\xcf\x83\xce\xb9\xce\xba\xce\xac',
           'is_IS': '\xce\x99\xcf\x83\xce\xbb\xce\xb1\xce\xbd\xce\xb4\xce\xb9\xce\xba\xce\xac',
           'da_DK': '\xce\x94\xce\xb1\xce\xbd\xce\xb9\xce\xba\xce\xac',
           'ar_AE': '\xce\x91\xcf\x81\xce\xb1\xce\xb2\xce\xb9\xce\xba\xce\xac',
           'sk_SK': 'Slovakian',
           'de_DE': '\xce\x93\xce\xb5\xcf\x81\xce\xbc\xce\xb1\xce\xbd\xce\xb9\xce\xba\xce\xac',
           'sr_YU': 'Serbian',
           'cs_CZ': '\xce\xa4\xcf\x83\xce\xad\xcf\x87\xce\xb9\xce\xba\xce\xb1',
           'pl_PL': '\xce\xa0\xce\xbf\xce\xbb\xcf\x89\xce\xbd\xce\xb9\xce\xba\xce\xac',
           'uk_UA': 'Ukrainian',
           'fa_IR': 'Persian',
           'sv_SE': '\xce\xa3\xce\xbf\xcf\x85\xce\xb9\xce\xb4\xce\xb5\xce\xb6\xce\xb9\xce\xba\xce\xac',
           'he_IL': 'Hebrew',
           'T1': 'Please use the UP and DOWN keys to select your language. Afterwards press the OK button.',
           'T2': '\xce\x95\xcf\x80\xce\xb9\xce\xbb\xce\xbf\xce\xb3\xce\xae \xce\xb3\xce\xbb\xcf\x8e\xcf\x83\xcf\x83\xce\xb1\xcf\x82'},
 'he_IL': {'tr_TR': '\xd7\x98\xd7\x95\xd7\xa8\xd7\xa7\xd7\x99\xd7\xaa',
           'fr_FR': '\xd7\xa6\xd7\xa8\xd7\xa4\xd7\xaa\xd7\x99\xd7\xaa',
           'fi_FI': '\xd7\xa4\xd7\x99\xd7\xa0\xd7\x99\xd7\xaa',
           'pt_PT': '\xd7\xa4\xd7\x95\xd7\xa8\xd7\x98\xd7\x95\xd7\x92\xd7\x96\xd7\x99\xd7\xaa',
           'fy_x-FY': 'Frisian',
           'it_IT': '\xd7\x90\xd7\x99\xd7\x98\xd7\x9c\xd7\xa7\xd7\x99\xd7\xaa',
           'et_EE': '\xd7\x90\xd7\xa1\xd7\x98\xd7\x95\xd7\xa0\xd7\x99\xd7\x94',
           'no_NO': '\xd7\xa0\xd7\x95\xd7\xa8\xd7\x95\xd7\x95\xd7\x92\xd7\x99\xd7\xaa',
           'nl_NL': '\xd7\x94\xd7\x95\xd7\x9c\xd7\xa0\xd7\x93\xd7\x99\xd7\xaa',
           'lv_LV': 'Latvian',
           'el_GR': '\xd7\x99\xd7\x95\xd7\x95\xd7\xa0\xd7\x99\xd7\xaa',
           'pt_BR_BR': 'Brazilian Portuguese',
           'hu_HU': '\xd7\x94\xd7\x95\xd7\xa0\xd7\x92\xd7\xa8\xd7\x99\xd7\xaa',
           'lt_LT': '\xd7\x9c\xd7\x99\xd7\x98\xd7\x90',
           'sl_SI': '\xd7\xa1\xd7\x9c\xd7\x95\xd7\x91\xd7\xa0\xd7\x99\xd7\xaa',
           'hr_HR': '\xd7\xa7\xd7\xa8\xd7\x95\xd7\x90\xd7\x98\xd7\x99\xd7\xaa',
           'en_EN': '\xd7\x90\xd7\xa0\xd7\x92\xd7\x9c\xd7\x99\xd7\xaa',
           'es_ES': '\xd7\xa1\xd7\xa4\xd7\xa8\xd7\x93\xd7\x99\xd7\xaa',
           'ca_AD': '\xd7\xa7\xd7\x98\xd7\x9c\xd7\x95\xd7\xa0\xd7\x99',
           'ru_RU': '\xd7\xa8\xd7\x95\xd7\xa1\xd7\x99\xd7\xaa',
           'is_IS': '\xd7\x90\xd7\x99\xd7\xa1\xd7\x9c\xd7\xa0\xd7\x93\xd7\x99\xd7\xaa',
           'da_DK': '\xd7\x93\xd7\xa0\xd7\x99\xd7\xaa',
           'ar_AE': '\xd7\xa2\xd7\xa8\xd7\x91\xd7\x99\xd7\xaa',
           'sk_SK': '\xd7\xa1\xd7\x9c\xd7\x95\xd7\x91\xd7\xa7\xd7\x99\xd7\x94',
           'de_DE': '\xd7\x92\xd7\xa8\xd7\x9e\xd7\xa0\xd7\x99\xd7\xaa',
           'sr_YU': '\xd7\xa1\xd7\xa8\xd7\x91\xd7\x99\xd7\xaa',
           'cs_CZ': "\xd7\xa6'\xd7\x9b\xd7\x99\xd7\xaa",
           'pl_PL': '\xd7\xa4\xd7\x95\xd7\x9c\xd7\xa0\xd7\x99\xd7\xaa',
           'uk_UA': '\xd7\x90\xd7\x95\xd7\xa7\xd7\xa8\xd7\x90\xd7\x99\xd7\xa0\xd7\x99\xd7\xaa',
           'fa_IR': 'Persian',
           'sv_SE': '\xd7\xa9\xd7\x95\xd7\x95\xd7\x93\xd7\x99\xd7\xaa',
           'he_IL': 'Hebrew',
           'T1': '.\xd7\x90\xd7\xa0\xd7\x90 \xd7\x91\xd7\x97\xd7\xa8 \xd7\x90\xd7\xaa \xd7\x94\xd7\xa9\xd7\xa4\xd7\x94, \xd7\x9c\xd7\x90\xd7\x97\xd7\xa8 \xd7\x9e\xd7\x9b\xd7\x9f \xd7\x9c\xd7\x97\xd7\xa5 \xd7\xa2\xd7\x9c \xd7\x90\xd7\xa9\xd7\xa8',
           'T2': '\xd7\x91\xd7\x97\xd7\x99\xd7\xa8\xd7\xaa \xd7\xa9\xd7\xa4\xd7\x94'},
 'hu_HU': {'tr_TR': 'T\xc3\xb6r\xc3\xb6k',
           'fr_FR': 'Francia',
           'fi_FI': 'Finn',
           'pt_PT': 'Portug\xc3\xa1l',
           'fy_x-FY': 'Fr\xc3\xadz',
           'it_IT': 'Olasz',
           'et_EE': '\xc3\x89szt',
           'no_NO': 'Norv\xc3\xa9g',
           'nl_NL': 'Holland',
           'lv_LV': 'Lett',
           'el_GR': 'G\xc3\xb6r\xc3\xb6g',
           'pt_BR_BR': 'Brazilian Portuguese',
           'hu_HU': 'Magyar',
           'lt_LT': 'Litv\xc3\xa1n',
           'sl_SI': 'Szolv\xc3\xa9n',
           'hr_HR': 'Horv\xc3\xa1t',
           'en_EN': 'Angol',
           'es_ES': 'Spanyol',
           'ca_AD': 'Katal\xc3\xa1n',
           'ru_RU': 'Orosz',
           'is_IS': 'Izlandi',
           'da_DK': 'D\xc3\xa1n',
           'ar_AE': 'Arab',
           'sk_SK': 'Szlov\xc3\xa1k',
           'de_DE': 'N\xc3\xa9met',
           'sr_YU': 'Szerb',
           'cs_CZ': 'Cseh',
           'pl_PL': 'Lengyel',
           'uk_UA': 'Ukr\xc3\xa1n',
           'fa_IR': 'Perzsa',
           'sv_SE': 'Sv\xc3\xa9d',
           'he_IL': 'Hebrew',
           'T1': 'K\xc3\xa9rem, haszn\xc3\xa1lja a FEL \xc3\xa9s LE gombokat a nyelv kiv\xc3\xa1laszt\xc3\xa1s\xc3\xa1hoz. Ez ut\xc3\xa1n nyomja le az OK gombot.',
           'T2': 'Nyelvv\xc3\xa1laszt\xc3\xa1s'},
 'lt_LT': {'tr_TR': 'Turk\xc5\xb3',
           'fr_FR': 'Pranc\xc5\xabz\xc5\xb3',
           'fi_FI': 'Suomi\xc5\xb3',
           'pt_PT': 'Portugal\xc5\xb3',
           'fy_x-FY': 'Friz\xc5\xb3',
           'it_IT': 'Ital\xc5\xb3',
           'et_EE': 'Est\xc5\xb3',
           'no_NO': 'Norveg\xc5\xb3',
           'nl_NL': 'Oland\xc5\xb3',
           'lv_LV': 'Latvi\xc5\xb3',
           'el_GR': 'Graik\xc5\xb3',
           'pt_BR_BR': 'Brazilian Portuguese',
           'hu_HU': 'Vengr\xc5\xb3',
           'lt_LT': 'Lietuvi\xc5\xb3',
           'sl_SI': 'Slov\xc4\x97n\xc5\xb3',
           'hr_HR': 'Kroat\xc5\xb3',
           'en_EN': 'Angl\xc5\xb3',
           'es_ES': 'Ispan\xc5\xb3',
           'ca_AD': 'Katalon\xc5\xb3',
           'ru_RU': 'Rus\xc5\xb3',
           'is_IS': 'Island\xc5\xb3',
           'da_DK': 'Dan\xc5\xb3',
           'ar_AE': 'Arab\xc5\xb3',
           'sk_SK': 'Slovak\xc5\xb3',
           'de_DE': 'Vokie\xc4\x8di\xc5\xb3',
           'sr_YU': 'Serb\xc5\xb3',
           'cs_CZ': '\xc4\x8cek\xc5\xb3',
           'pl_PL': 'Lenk\xc5\xb3',
           'uk_UA': 'Ukrainie\xc4\x8di\xc5\xb3',
           'fa_IR': 'Pers\xc5\xb3',
           'sv_SE': '\xc5\xa0ved\xc5\xb3',
           'he_IL': 'Hebraj\xc5\xb3',
           'T1': 'Pra\xc5\xa1ome naudoti AUK\xc5\xa0TYN IR \xc5\xbdEMYN mygtukus, kad i\xc5\xa1sirinktum\xc4\x97te savo kalb\xc4\x85. Po to spauskite OK mygtuk\xc4\x85.',
           'T2': 'Kalbos pasirinkimas'},
 'lv_LV': {'tr_TR': 'Turku',
           'fr_FR': 'Fran\xc4\x8du',
           'fi_FI': 'Somu',
           'pt_PT': 'Portug\xc4\x81\xc4\xbcu',
           'fy_x-FY': 'Fr\xc4\xabzu',
           'it_IT': 'It\xc4\x81\xc4\xbcu',
           'et_EE': 'Estonian',
           'no_NO': 'Norv\xc4\x93\xc4\xa3u',
           'nl_NL': 'Holandie\xc5\xa1u',
           'lv_LV': 'Latvie\xc5\xa1u',
           'el_GR': 'Grie\xc4\xb7u',
           'pt_BR_BR': 'Brazilian Portuguese',
           'hu_HU': 'Ung\xc4\x81ru',
           'lt_LT': 'Lietuvie\xc5\xa1u',
           'sl_SI': 'Slovenian',
           'hr_HR': 'Horv\xc4\x81tu',
           'en_EN': 'Ang\xc4\xbcu',
           'es_ES': 'Sp\xc4\x81\xc5\x86u',
           'ca_AD': 'Kat\xc4\x81lie\xc5\xa1u',
           'ru_RU': 'Krievu',
           'is_IS': 'Islandie\xc5\xa1u',
           'da_DK': 'D\xc4\x81\xc5\x86u',
           'ar_AE': 'Ar\xc4\x81bu',
           'sk_SK': 'Slovakian',
           'de_DE': 'V\xc4\x81cu',
           'sr_YU': 'Serbian',
           'cs_CZ': '\xc4\x8cehu',
           'pl_PL': 'Po\xc4\xbcu',
           'uk_UA': 'Ukrai\xc5\x86u',
           'fa_IR': 'Persian',
           'sv_SE': 'Zviedru',
           'he_IL': 'Hebrew',
           'T1': 'L\xc5\xabdzu lietojiet UP un DOWN tausti\xc5\x86us, lai izv\xc4\x93l\xc4\x93tos valodu. P\xc4\x93c tam spiediet OK.',
           'T2': 'Valodas izv\xc4\x93le'},
 'is_IS': {'tr_TR': 'Tyrkneska',
           'fr_FR': 'Franska',
           'fi_FI': 'Finnska',
           'pt_PT': 'Port\xc3\xbagalska',
           'fy_x-FY': 'Fr\xc3\xadsneska',
           'it_IT': '\xc3\x8dtalska',
           'et_EE': 'Eistneska',
           'no_NO': 'Norska',
           'nl_NL': 'Hollenska',
           'lv_LV': 'Lettneska',
           'el_GR': 'Gr\xc3\xadska',
           'pt_BR_BR': 'Brazilian Portuguese',
           'hu_HU': 'Ungverska',
           'lt_LT': 'Lith\xc3\xa1\xc3\xadska',
           'sl_SI': 'Slovenian',
           'hr_HR': 'Kr\xc3\xb3at\xc3\xadska',
           'en_EN': 'Enska',
           'es_ES': 'Sp\xc3\xa6nska',
           'ca_AD': 'Katal\xc3\xb3nska',
           'ru_RU': 'R\xc3\xbassneska',
           'is_IS': '\xc3\x8dslenska',
           'da_DK': 'Danska',
           'ar_AE': 'Arab\xc3\xadska',
           'sk_SK': 'Slovakian',
           'de_DE': '\xc3\x9e\xc3\xbdska',
           'sr_YU': 'Serneska',
           'cs_CZ': 'T\xc3\xa9kkneska',
           'pl_PL': 'P\xc3\xb3lska',
           'uk_UA': 'Ukrainian',
           'fa_IR': 'Persneska',
           'sv_SE': 'S\xc3\xa6nskt',
           'he_IL': 'Hebrew',
           'T1': 'Vinsamlega noti\xc3\xb0 UP og NI\xc3\x90UR takka til a\xc3\xb0 velja tungum\xc3\xa1l. \xc3\x9dttu svo \xc3\xa1 OK til a\xc3\xb0 nota.',
           'T2': 'Val tungum\xc3\xa1ls'},
 'it_IT': {'tr_TR': 'Turco',
           'fr_FR': 'Francese',
           'fi_FI': 'Finlandese',
           'pt_PT': 'Portoghese',
           'fy_x-FY': 'Frisone',
           'it_IT': 'Italiano',
           'et_EE': 'Estone',
           'no_NO': 'Norvegese',
           'nl_NL': 'Olandese',
           'lv_LV': 'Lettone',
           'el_GR': 'Greco',
           'pt_BR_BR': 'Brazilian Portuguese',
           'hu_HU': 'Ungherese',
           'lt_LT': 'Lituano',
           'sl_SI': 'Sloveno',
           'hr_HR': 'Croato',
           'en_EN': 'Inglese',
           'es_ES': 'Spagnolo',
           'ca_AD': 'Catalano',
           'ru_RU': 'Russo',
           'is_IS': 'Islandese',
           'da_DK': 'Danese',
           'ar_AE': 'Arabo',
           'sk_SK': 'Slovacco',
           'de_DE': 'Tedesco',
           'sr_YU': 'Serbo',
           'cs_CZ': 'Ceco',
           'pl_PL': 'Polacco',
           'uk_UA': 'Ucraino',
           'fa_IR': 'Persiano',
           'sv_SE': 'Svedese',
           'he_IL': 'Ebraico',
           'T1': 'Selezionare la propria lingua utilizzando i tasti S\xc3\xb9/Gi\xc3\xb9. OK >> confermare.',
           'T2': 'Selezione lingua'},
 'no_NO': {'tr_TR': 'Tyrkisk',
           'fr_FR': 'Fransk',
           'fi_FI': 'Finsk',
           'pt_PT': 'Portugisisk',
           'fy_x-FY': 'Frisisk',
           'it_IT': 'Italiensk',
           'et_EE': 'Estlandsk',
           'no_NO': 'Norsk',
           'nl_NL': 'Nederlandsk',
           'lv_LV': 'Latvisk',
           'el_GR': 'Gresk',
           'pt_BR_BR': 'Brazilian Portuguese',
           'hu_HU': 'Ungarsk',
           'lt_LT': 'Litauisk',
           'sl_SI': 'Slovenisk',
           'hr_HR': 'Kroatisk',
           'en_EN': 'Engelsk',
           'es_ES': 'Spansk',
           'ca_AD': 'Katalansk',
           'ru_RU': 'Russisk',
           'is_IS': 'Islandsk',
           'da_DK': 'Dansk',
           'ar_AE': 'Arabisk',
           'sk_SK': 'Slovakisk',
           'de_DE': 'Tysk',
           'sr_YU': 'Serbisk',
           'cs_CZ': 'Tjekkisk',
           'pl_PL': 'Polsk',
           'uk_UA': 'Ukrainsk',
           'fa_IR': 'Persisk',
           'sv_SE': 'Svensk',
           'he_IL': 'Hebraisk',
           'T1': 'Vennligst bruk OPP og NED taster for \xc3\xa5 velge spr\xc3\xa5k. Etterp\xc3\xa5 trykker du OK tast for \xc3\xa5 fortsette.',
           'T2': 'Spr\xc3\xa5kvalg'},
 'fa_IR': {'tr_TR': '\xd8\xaa\xd8\xb1\xda\xa9\xdb\x8c',
           'fr_FR': '\xd9\x81\xd8\xb1\xd8\xa7\xd9\x86\xd8\xb3\xd9\x88\xdb\x8c',
           'fi_FI': '\xd9\xbe\xd8\xa7\xdb\x8c\xd8\xa7\xd9\x86',
           'pt_PT': '\xd9\xbe\xd8\xb1\xd8\xaa\xd8\xba\xd8\xa7\xd9\x84\xdb\x8c',
           'fy_x-FY': '\xd9\x81\xd8\xb1\xdb\x8c\xd8\xb2\xdb\x8c',
           'it_IT': '\xd8\xa7\xdb\x8c\xd8\xaa\xd8\xa7\xd9\x84\xdb\x8c\xd8\xa7\xdb\x8c\xdb\x8c',
           'et_EE': '\xd8\xa7\xd8\xb3\xd8\xaa\xd9\x88\xd9\x86\xdb\x8c\xd8\xa7\xdb\x8c\xdb\x8c',
           'no_NO': '\xd9\x86\xd8\xb1\xd9\x88\xda\x98\xdb\x8c',
           'nl_NL': '\xd9\x81\xd9\x84\xd9\x85\xd9\x86\xda\xa9\xdb\x8c',
           'lv_LV': '\xd9\x84\xd8\xaa\xd9\x88\xd9\x86\xdb\x8c',
           'el_GR': '\xdb\x8c\xd9\x88\xd9\x86\xd8\xa7\xd9\x86\xdb\x8c',
           'pt_BR_BR': 'Brazilian Portuguese',
           'hu_HU': '\xd9\x85\xd8\xac\xd8\xa7\xd8\xb1\xd8\xb3\xd8\xaa\xd8\xa7\xd9\x86\xdb\x8c',
           'lt_LT': '\xd9\x84\xdb\x8c\xd8\xaa\xd9\x88\xd8\xa7\xd9\x86\xdb\x8c',
           'sl_SI': '\xd8\xa7\xd8\xb3\xd9\x84\xd9\x88\xd9\x88\xd9\x86\xdb\x8c\xd8\xa7\xdb\x8c\xdb\x8c',
           'hr_HR': '\xda\xa9\xd8\xb1\xd9\x88\xd8\xa7\xd8\xb3\xdb\x8c',
           'en_EN': '\xd8\xa7\xd9\x86\xda\xaf\xd9\x84\xdb\x8c\xd8\xb3\xdb\x8c',
           'es_ES': '\xd8\xa7\xd8\xb3\xd9\xbe\xd8\xa7\xd9\x86\xdb\x8c\xd8\xa7\xdb\x8c\xdb\x8c',
           'ca_AD': '\xda\xa9\xd8\xa7\xd8\xaa\xd8\xa7\xd9\x84\xd8\xa7\xd9\x86',
           'ru_RU': '\xd8\xb1\xd9\x88\xd8\xb3\xdb\x8c',
           'is_IS': '\xd8\xa7\xdb\x8c\xd8\xb3\xd9\x84\xd9\x86\xd8\xaf\xdb\x8c',
           'da_DK': '\xd8\xaf\xd8\xa7\xd9\x86\xd9\x85\xd8\xa7\xd8\xb1\xda\xa9\xdb\x8c',
           'ar_AE': '\xd8\xb9\xd8\xb1\xd8\xa8\xdb\x8c',
           'sk_SK': '\xd8\xa7\xd8\xb3\xd9\x84\xd9\x88\xd8\xa7\xda\xa9\xdb\x8c',
           'de_DE': '\xd8\xa2\xd9\x84\xd9\x85\xd8\xa7\xd9\x86\xdb\x8c',
           'sr_YU': '\xd8\xb5\xd8\xb1\xd8\xa8\xd8\xb3\xd8\xaa\xd8\xa7\xd9\x86\xdb\x8c',
           'cs_CZ': '\xda\x86\xda\xa9\xd9\x88\xd8\xb3\xd9\x84\xd9\x88\xd8\xa7\xda\xa9\xdb\x8c',
           'pl_PL': '\xd9\x84\xd9\x87\xd8\xb3\xd8\xaa\xd8\xa7\xd9\x86\xdb\x8c',
           'uk_UA': '\xd8\xa7\xd9\x88\xda\xa9\xd8\xb1\xd8\xa7\xdb\x8c\xd9\x86\xdb\x8c',
           'fa_IR': '\xd9\x81\xd8\xa7\xd8\xb1\xd8\xb3\xdb\x8c',
           'sv_SE': '\xd8\xb3\xd9\x88\xd8\xa6\xd8\xaf\xdb\x8c',
           'he_IL': '\xd8\xb9\xd8\xa8\xd8\xb1\xdb\x8c',
           'T1': 'Please use the UP and DOWN keys to select your language. Afterwards press the OK button.',
           'T2': '\xd8\xa7\xd9\x86\xd8\xaa\xd8\xae\xd8\xa7\xd8\xa8 \xd8\xb2\xd8\xa8\xd8\xa7\xd9\x86'},
 'pl_PL': {'tr_TR': 'Turecki',
           'fr_FR': 'Francuski',
           'fi_FI': 'Fi\xc5\x84ski',
           'pt_PT': 'Portugalski',
           'fy_x-FY': 'Fryzyjski',
           'it_IT': 'W\xc5\x82oski',
           'et_EE': 'Esto\xc5\x84ski',
           'no_NO': 'Norweski',
           'nl_NL': 'Holenderski',
           'lv_LV': '\xc5\x81otewski',
           'el_GR': 'Grecki',
           'pt_BR_BR': 'Brazilian Portuguese',
           'hu_HU': 'W\xc4\x99gierski',
           'lt_LT': 'Litewski',
           'sl_SI': 'S\xc5\x82owe\xc5\x84ski',
           'hr_HR': 'Chorwacki',
           'en_EN': 'Angielski',
           'es_ES': 'Hiszpa\xc5\x84ski',
           'ca_AD': 'Hiszpa\xc5\x84ski',
           'ru_RU': 'Rosyjski',
           'is_IS': 'Islandzki',
           'da_DK': 'Du\xc5\x84ski',
           'ar_AE': 'Arabski',
           'sk_SK': 'S\xc5\x82owacki',
           'de_DE': 'Niemiecki',
           'sr_YU': 'Serbski',
           'cs_CZ': 'Czeski',
           'pl_PL': 'Polski',
           'uk_UA': 'Ukrai\xc5\x84ski',
           'fa_IR': 'Perski',
           'sv_SE': 'Szwedzki',
           'he_IL': 'Hebrajski',
           'T1': 'W celu wyboru j\xc4\x99zyka u\xc5\xbcyj klawiszy G\xc3\x93RA i D\xc3\x93\xc5\x81. Nastepnie nacisnij przycisk OK.',
           'T2': 'Wyb\xc3\xb3r j\xc4\x99zyka'},
 'pt_PT': {'tr_TR': 'Turco',
           'fr_FR': 'Franc\xc3\xaas',
           'fi_FI': 'Finland\xc3\xaas',
           'pt_PT': 'Portugu\xc3\xaas',
           'fy_x-FY': 'Frisian',
           'it_IT': 'Italiano',
           'et_EE': 'Estonian',
           'no_NO': 'Noruegu\xc3\xaas',
           'nl_NL': 'Holand\xc3\xaas',
           'lv_LV': 'Latvian',
           'el_GR': 'Grego',
           'pt_BR_BR': 'Brazilian Portuguese',
           'hu_HU': 'Hungaro',
           'lt_LT': 'Lituano',
           'sl_SI': 'Slovenian',
           'hr_HR': 'Croata',
           'en_EN': 'Ingl\xc3\xaas',
           'es_ES': 'Catal\xc3\xa3o',
           'ca_AD': 'Catal\xc3\xa3o',
           'ru_RU': 'Russo',
           'is_IS': 'Island\xc3\xaas',
           'da_DK': 'Dinamarqu\xc3\xaas',
           'ar_AE': 'Arabe',
           'sk_SK': 'Slovakian',
           'de_DE': 'Alem\xc3\xa3o',
           'sr_YU': 'Serbian',
           'cs_CZ': 'Checo',
           'pl_PL': 'Polaco',
           'uk_UA': 'Ukrainian',
           'fa_IR': 'Persian',
           'sv_SE': 'Sueco',
           'he_IL': 'Hebrew',
           'T1': 'Please use the UP and DOWN keys to select your language. Afterwards press the OK button.',
           'T2': 'Selec\xc3\xa7\xc3\xa3o do Idioma'},
 'ru_RU': {'tr_TR': '\xd0\xa2\xd1\x83\xd1\x80\xd0\xb5\xd1\x86\xd0\xba\xd0\xb8\xd0\xb9',
           'fr_FR': '\xd0\xa4\xd1\x80\xd0\xb0\xd0\xbd\xd1\x86\xd1\x83\xd0\xb7\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9',
           'fi_FI': '\xd0\xa4\xd0\xb8\xd0\xbd\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9',
           'pt_PT': '\xd0\x9f\xd0\xbe\xd1\x80\xd1\x82\xd1\x83\xd0\xb3\xd0\xb0\xd0\xbb\xd1\x8c\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9',
           'fy_x-FY': '\xd0\xa4\xd1\x80\xd0\xb8\xd0\xb7\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9',
           'it_IT': '\xd0\x98\xd1\x82\xd0\xb0\xd0\xbb\xd1\x8c\xd1\x8f\xd0\xbd\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9',
           'et_EE': 'Estonian',
           'no_NO': '\xd0\x9d\xd0\xbe\xd1\x80\xd0\xb2\xd0\xb5\xd0\xb6\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9',
           'nl_NL': '\xd0\x9d\xd0\xb8\xd0\xb4\xd0\xb5\xd1\x80\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb4\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9',
           'lv_LV': '\xd0\x9b\xd0\xb0\xd1\x82\xd0\xb2\xd0\xb8\xd0\xb9\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9',
           'el_GR': '\xd0\x93\xd1\x80\xd0\xb5\xd1\x87\xd0\xb5\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9',
           'pt_BR_BR': 'Brazilian Portuguese',
           'hu_HU': '\xd0\x92\xd0\xb5\xd0\xbd\xd0\xb3\xd0\xb5\xd1\x80\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9',
           'lt_LT': '\xd0\x9b\xd0\xb8\xd1\x82\xd0\xbe\xd0\xb2\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9',
           'sl_SI': 'Slovenian',
           'hr_HR': '\xd0\xa5\xd0\xbe\xd1\x80\xd0\xb2\xd0\xb0\xd1\x82\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9',
           'en_EN': '\xd0\x90\xd0\xbd\xd0\xb3\xd0\xbb\xd0\xb8\xd0\xb9\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9',
           'es_ES': '\xd0\x98\xd1\x81\xd0\xbf\xd0\xb0\xd0\xbd\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9',
           'ca_AD': '\xd0\x9a\xd0\xb0\xd1\x82\xd0\xb0\xd0\xbb\xd0\xbe\xd0\xbd\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9',
           'ru_RU': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9',
           'is_IS': '\xd0\x98\xd1\x81\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb4\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9',
           'da_DK': '\xd0\x94\xd0\xb0\xd1\x82\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9',
           'ar_AE': '\xd0\x90\xd1\x80\xd0\xb0\xd0\xb1\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9',
           'sk_SK': 'Slovakian',
           'de_DE': '\xd0\x9d\xd0\xb5\xd0\xbc\xd0\xb5\xd1\x86\xd0\xba\xd0\xb8\xd0\xb9',
           'sr_YU': 'Serbian',
           'cs_CZ': '\xd0\xa7\xd0\xb5\xd1\x88\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9',
           'pl_PL': '\xd0\x9f\xd0\xbe\xd0\xbb\xd1\x8c\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9',
           'uk_UA': '\xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9',
           'fa_IR': 'Persian',
           'sv_SE': '\xd0\xa8\xd0\xb2\xd0\xb5\xd0\xb4\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9',
           'he_IL': 'Hebrew',
           'T1': '\xd0\x9f\xd0\xbe\xd0\xb6\xd0\xb0\xd0\xbb\xd1\x83\xd0\xb9\xd1\x81\xd1\x82\xd0\xb0, \xd0\xb8\xd1\x81\xd0\xbf\xd0\xbe\xd0\xbb\xd1\x8c\xd0\xb7\xd1\x83\xd0\xb9\xd1\x82\xd0\xb5 \xd0\xba\xd0\xbd\xd0\xbe\xd0\xbf\xd0\xba\xd0\xb8 \xd0\x92\xd0\x92\xd0\x95\xd0\xa0\xd0\xa5 \xd0\xb8 \xd0\x92\xd0\x9d\xd0\x98\xd0\x97 \xd0\xb4\xd0\xbb\xd1\x8f \xd0\xb2\xd1\x8b\xd0\xb1\xd0\xbe\xd1\x80\xd0\xb0 \xd1\x8f\xd0\xb7\xd1\x8b\xd0\xba\xd0\xb0. \xd0\x94\xd0\xb0\xd0\xbb\xd0\xb5\xd0\xb5 \xd0\xbd\xd0\xb0\xd0\xb6\xd0\xbc\xd0\xb8\xd1\x82\xd0\xb5 \xd0\x9e\xd0\x9a.',
           'T2': '\xd0\x92\xd1\x8b\xd0\xb1\xd0\xbe\xd1\x80 \xd1\x8f\xd0\xb7\xd1\x8b\xd0\xba\xd0\xb0'},
 'sr_YU': {'tr_TR': 'Turski',
           'fr_FR': 'Francuski',
           'fi_FI': 'Finski',
           'pt_PT': 'Portugalski',
           'fy_x-FY': 'Frizijski',
           'it_IT': 'Italijanski',
           'et_EE': 'Estonski',
           'no_NO': 'Norve\xc5\xa1ki',
           'nl_NL': 'Holandski',
           'lv_LV': 'Letonski',
           'el_GR': 'Gr\xc4\x8dki',
           'pt_BR_BR': 'Brazilian Portuguese',
           'hu_HU': 'Ma\xc4\x91arski',
           'lt_LT': 'Litvanski',
           'sl_SI': 'Slovena\xc4\x8dki',
           'hr_HR': 'Hrvatski',
           'en_EN': 'Engleski',
           'es_ES': '\xc5\xa0panski',
           'ca_AD': 'Katalonski',
           'ru_RU': 'Ruski',
           'is_IS': 'Islandski',
           'da_DK': 'Danski',
           'ar_AE': 'Arapski',
           'sk_SK': 'Slova\xc4\x8dki',
           'de_DE': 'Nema\xc4\x8dki',
           'sr_YU': 'Srpski',
           'cs_CZ': '\xc4\x8ce\xc5\xa1ki',
           'pl_PL': 'Poljski',
           'uk_UA': 'Ukrajinski',
           'fa_IR': 'Persijski',
           'sv_SE': '\xc5\xa0vedski',
           'he_IL': 'Hebrew',
           'T1': 'Molim koristite UP i DOWN tipke da izaberete jezik.Posle toga pritisnite OK dugme.',
           'T2': 'Izbor jezika'},
 'sk_SK': {'tr_TR': 'Ture\xc4\x8dtina',
           'fr_FR': 'Franc\xc3\xbaz\xc5\xa1tina',
           'fi_FI': 'F\xc3\xadn\xc4\x8dina',
           'pt_PT': 'Portugal\xc4\x8dina',
           'fy_x-FY': 'Fr\xc3\xadz\xc5\xa1tina',
           'it_IT': 'Talian\xc4\x8dina',
           'et_EE': 'Est\xc3\xb3n\xc4\x8dina',
           'no_NO': 'N\xc3\xb3r\xc4\x8dina',
           'nl_NL': 'Holand\xc4\x8dina',
           'lv_LV': 'Loty\xc5\xa1\xc4\x8dina',
           'el_GR': 'Gr\xc3\xa9\xc4\x8dtina',
           'pt_BR_BR': 'Brazilian Portuguese',
           'hu_HU': 'Ma\xc4\x8far\xc4\x8dina',
           'lt_LT': 'Litov\xc4\x8dina',
           'sl_SI': 'Slovin\xc4\x8dina',
           'hr_HR': 'Chorv\xc3\xa1t\xc4\x8dina',
           'en_EN': 'Angli\xc4\x8dtina',
           'es_ES': '\xc5\xa0paniel\xc4\x8dina',
           'ca_AD': 'Katal\xc3\xa1n\xc4\x8dina',
           'ru_RU': 'Ru\xc5\xa1tina',
           'is_IS': 'Island\xc4\x8dina',
           'da_DK': 'D\xc3\xa1n\xc4\x8dina',
           'ar_AE': 'Arab\xc4\x8dina',
           'sk_SK': 'Sloven\xc4\x8dina',
           'de_DE': 'Nem\xc4\x8dina',
           'sr_YU': 'Srb\xc4\x8dina',
           'cs_CZ': '\xc4\x8ce\xc5\xa1tina',
           'pl_PL': 'Po\xc4\xbe\xc5\xa1tina',
           'uk_UA': 'Ukrajin\xc4\x8dina',
           'fa_IR': 'Perz\xc5\xa1tina',
           'sv_SE': '\xc5\xa0v\xc3\xa9d\xc4\x8dina',
           'he_IL': 'Hebrej\xc4\x8dina',
           'T1': 'Tla\xc4\x8didlami NAHOR alebo NADOL zvo\xc4\xbete jazyk. Potom stla\xc4\x8dte tla\xc4\x8didlo OK.',
           'T2': 'Vo\xc4\xbeba jazyka'},
 'sl_SI': {'tr_TR': 'Tur\xc5\xa1ko',
           'fr_FR': 'Francosko',
           'fi_FI': 'Finsko',
           'pt_PT': 'Portugalsko',
           'fy_x-FY': 'Frisian',
           'it_IT': 'Italjansko',
           'et_EE': 'Estonian',
           'no_NO': 'Norve\xc5\xa1ki',
           'nl_NL': 'Nizozemsko',
           'lv_LV': 'Latvian',
           'el_GR': 'Gr\xc5\xa1ko',
           'pt_BR_BR': 'Brazilian Portuguese',
           'hu_HU': 'Mad\xc5\xbearsko',
           'lt_LT': 'Litvansko',
           'sl_SI': 'Slovensko',
           'hr_HR': 'Hrva\xc5\xa1ko',
           'en_EN': 'Angle\xc5\xa1ko',
           'es_ES': '\xc5\xa0pansko',
           'ca_AD': 'Katalonski',
           'ru_RU': 'Rusko',
           'is_IS': 'Islandsko',
           'da_DK': 'Dansko',
           'ar_AE': 'Arabsko',
           'sk_SK': 'Slovakian',
           'de_DE': 'Nem\xc5\xa1ko',
           'sr_YU': 'Serbian',
           'cs_CZ': '\xc4\x8ce\xc5\xa1ko',
           'pl_PL': 'Poljsko',
           'uk_UA': 'Ukrajinsko',
           'fa_IR': 'Persian',
           'sv_SE': '\xc5\xa0vedsko',
           'he_IL': 'Hebrew',
           'T1': 'Prosim uporabite tipke GOR in DOL za izbiro jezika in pritisnite OK tipko za potrditev.',
           'T2': 'Izberite jezik'},
 'es_ES': {'tr_TR': 'Turco',
           'fr_FR': 'Franc\xc3\xa9s',
           'fi_FI': 'Finland\xc3\xa9s',
           'pt_PT': 'Portugu\xc3\xa9s',
           'fy_x-FY': 'Fris\xc3\xb3n',
           'it_IT': 'Italiano',
           'et_EE': 'Estonio',
           'no_NO': 'Noruego',
           'nl_NL': 'Alem\xc3\xa1n',
           'lv_LV': 'Let\xc3\xb3n',
           'el_GR': 'Griego',
           'pt_BR_BR': 'Brazilian Portuguese',
           'hu_HU': 'H\xc3\xbangaro',
           'lt_LT': 'Lituano',
           'sl_SI': 'Esloveno',
           'hr_HR': 'Croata',
           'en_EN': 'Ingl\xc3\xa9s',
           'es_ES': 'Espa\xc3\xb1ol',
           'ca_AD': 'Catal\xc3\xa1n',
           'ru_RU': 'Ruso',
           'is_IS': 'Island\xc3\xa9s',
           'da_DK': 'Dan\xc3\xa9s',
           'ar_AE': 'Ar\xc3\xa1bigo',
           'sk_SK': 'Eslovaco',
           'de_DE': 'Alem\xc3\xa1n',
           'sr_YU': 'Servio',
           'cs_CZ': 'Checo',
           'pl_PL': 'Polaco',
           'uk_UA': 'Ucraniano',
           'fa_IR': 'Persa',
           'sv_SE': 'Sueco',
           'he_IL': 'Hebrew',
           'T1': 'Use las teclas ARRIBA y ABAJO para seleccionar su idioma. Despu\xc3\xa9s, pulse el bot\xc3\xb3n OK.',
           'T2': 'Selecci\xc3\xb3n de idioma'},
 'sv_SE': {'tr_TR': 'Turkiska',
           'fr_FR': 'Franska',
           'fi_FI': 'Finska',
           'pt_PT': 'Portugisiska',
           'fy_x-FY': 'Frisiska',
           'it_IT': 'Italienska',
           'et_EE': 'Estniska',
           'no_NO': 'Norska',
           'nl_NL': 'Holl\xc3\xa4ndska',
           'lv_LV': 'Lettiska',
           'el_GR': 'Grekiska',
           'pt_BR_BR': 'Brazilian Portuguese',
           'hu_HU': 'Ungerska',
           'lt_LT': 'Litauiska',
           'sl_SI': 'Slovenska',
           'hr_HR': 'Kroatiska',
           'en_EN': 'Engelska',
           'es_ES': 'Spanska',
           'ca_AD': 'Katalanska',
           'ru_RU': 'Ryska',
           'is_IS': 'Isl\xc3\xa4ndska',
           'da_DK': 'Danska',
           'ar_AE': 'Arabiska',
           'sk_SK': 'Slovakisk',
           'de_DE': 'Tyska',
           'sr_YU': 'Serbiska',
           'cs_CZ': 'Tjeckiska',
           'pl_PL': 'Polska',
           'uk_UA': 'Ukrainska',
           'fa_IR': 'Persiska',
           'sv_SE': 'Svenska',
           'he_IL': 'Hebreiska',
           'T1': 'V\xc3\xa4nligen anv\xc3\xa4nd UPP och NER pil f\xc3\xb6r att v\xc3\xa4lja spr\xc3\xa5k. Efter val tryck p\xc3\xa5 OK knappen.',
           'T2': 'V\xc3\xa4lj spr\xc3\xa5k'},
 'tr_TR': {'tr_TR': 'T\xc3\xbcrk\xc3\xa7e',
           'fr_FR': 'Frans\xc4\xb1zca',
           'fi_FI': 'Fince',
           'pt_PT': 'Portekizce',
           'fy_x-FY': 'Frizyece',
           'it_IT': '\xc4\xb0talyanca',
           'et_EE': 'Est\xc3\xa7e',
           'no_NO': 'Norve\xc3\xa7\xc3\xa7e',
           'nl_NL': 'Flemenk\xc3\xa7e',
           'lv_LV': 'Letonca',
           'el_GR': 'Yunanca',
           'pt_BR_BR': 'Brazilian Portuguese',
           'hu_HU': 'Macarca',
           'lt_LT': 'Litvanyaca',
           'sl_SI': 'Slovence',
           'hr_HR': 'H\xc4\xb1rvat\xc3\xa7a',
           'en_EN': '\xc4\xb0ngilizce',
           'es_ES': '\xc4\xb0spanyolca',
           'ca_AD': 'Katalanca',
           'ru_RU': 'Rus\xc3\xa7a',
           'is_IS': '\xc4\xb0zlandaca',
           'da_DK': 'Danca',
           'ar_AE': 'Arap\xc3\xa7a',
           'sk_SK': 'Slovak\xc3\xa7a',
           'de_DE': 'Almanca',
           'sr_YU': 'S\xc4\xb1rp\xc3\xa7a',
           'cs_CZ': '\xc3\x87ek\xc3\xa7e',
           'pl_PL': 'Leh\xc3\xa7e',
           'uk_UA': 'Ukraynaca',
           'fa_IR': 'Fars\xc3\xa7a',
           'sv_SE': '\xc4\xb0sve\xc3\xa7\xc3\xa7e',
           'he_IL': 'Hebrew',
           'T1': 'Dil se\xc3\xa7iminizi, yapmak i\xc3\xa7in YUKARI ve A\xc5\x9eA\xc4\x9eI tu\xc5\x9flar\xc4\xb1n\xc4\xb1, onaylamak i\xc3\xa7in OK tu\xc5\x9funu kullan\xc4\xb1n.',
           'T2': 'Dil se\xc3\xa7imi'},
 'uk_UA': {'tr_TR': '\xd0\xa2\xd1\x83\xd1\x80\xd0\xb5\xd1\x86\xd1\x8c\xd0\xba\xd0\xb0',
           'fr_FR': '\xd0\xa4\xd1\x80\xd0\xb0\xd0\xbd\xd1\x86\xd1\x83\xd0\xb7\xd1\x8c\xd0\xba\xd0\xb0',
           'fi_FI': '\xd0\xa4\xd1\x96\xd0\xbd\xd1\x81\xd1\x8c\xd0\xba\xd0\xb0',
           'pt_PT': '\xd0\x9f\xd0\xbe\xd1\x80\xd1\x82\xd1\x83\xd0\xb3\xd0\xb0\xd0\xbb\xd1\x8c\xd1\x81\xd1\x8c\xd0\xba\xd0\xb0',
           'fy_x-FY': '\xd0\xa4\xd1\x80\xd1\x96\xd0\xb7\xd1\x96\xd0\xb9\xd1\x81\xd1\x8c\xd0\xba\xd0\xb0',
           'it_IT': '\xd0\x86\xd1\x82\xd0\xb0\xd0\xbb\xd1\x96\xd0\xb9\xd1\x81\xd1\x8c\xd0\xba\xd0\xb0',
           'et_EE': 'Estonian',
           'no_NO': '\xd0\x9d\xd0\xbe\xd1\x80\xd0\xb2\xd0\xb5\xd0\xb6\xd1\x81\xd1\x8c\xd0\xba\xd0\xb0',
           'nl_NL': '\xd0\x93\xd0\xbe\xd0\xbb\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb4\xd1\x81\xd1\x8c\xd0\xba\xd0\xb0',
           'lv_LV': '\xd0\x9b\xd0\xb0\xd1\x82\xd0\xb2\xd1\x96\xd0\xb9\xd1\x81\xd1\x8c\xd0\xba\xd0\xb0',
           'el_GR': '\xd0\x93\xd1\x80\xd0\xb5\xd1\x86\xd1\x8c\xd0\xba\xd0\xb0',
           'pt_BR_BR': 'Brazilian Portuguese',
           'hu_HU': '\xd0\xa3\xd0\xb3\xd0\xbe\xd1\x80\xd1\x81\xd1\x8c\xd0\xba\xd0\xb0',
           'lt_LT': '\xd0\x9b\xd0\xb8\xd1\x82\xd0\xbe\xd0\xb2\xd1\x81\xd1\x8c\xd0\xba\xd0\xb0',
           'sl_SI': 'Slovenian',
           'hr_HR': '\xd0\xa5\xd0\xbe\xd1\x80\xd0\xb2\xd0\xb0\xd1\x82\xd1\x8c\xd1\x81\xd0\xba\xd0\xb0',
           'en_EN': '\xd0\x90\xd0\xbd\xd0\xb3\xd0\xbb\xd1\x96\xd0\xb9\xd1\x81\xd1\x8c\xd0\xba\xd0\xb0',
           'es_ES': '\xd0\x86\xd1\x81\xd0\xbf\xd0\xb0\xd0\xbd\xd1\x81\xd1\x8c\xd0\xba\xd0\xb0',
           'ca_AD': '\xd0\x9a\xd0\xb0\xd1\x82\xd0\xb0\xd0\xbb\xd0\xbe\xd0\xbd\xd1\x81\xd1\x8c\xd0\xba\xd0\xb0',
           'ru_RU': '\xd0\xa0\xd0\xbe\xd1\x81\xd1\x96\xd0\xb9\xd1\x81\xd1\x8c\xd0\xba\xd0\xb0',
           'is_IS': '\xd0\x86\xd1\x81\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb4\xd1\x81\xd1\x8c\xd0\xba\xd0\xb0',
           'da_DK': '\xd0\x94\xd0\xb0\xd0\xbd\xd1\x81\xd1\x8c\xd0\xba\xd0\xb0',
           'ar_AE': '\xd0\x90\xd1\x80\xd0\xb0\xd0\xb1\xd1\x81\xd1\x8c\xd0\xba\xd0\xb8\xd0\xb9',
           'sk_SK': 'Slovakian',
           'de_DE': '\xd0\x9d\xd1\x96\xd0\xbc\xd0\xb5\xd1\x86\xd1\x8c\xd0\xba\xd0\xb0',
           'sr_YU': '\xd0\xa1\xd0\xb5\xd1\x80\xd0\xb1\xd1\x81\xd1\x8c\xd0\xba\xd0\xb0',
           'cs_CZ': '\xd0\xa7\xd0\xb5\xd1\x88\xd1\x81\xd1\x8c\xd0\xba\xd0\xb0',
           'pl_PL': '\xd0\x9f\xd0\xbe\xd0\xbb\xd1\x8c\xd1\x81\xd1\x8c\xd0\xba\xd0\xb0',
           'uk_UA': '\xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd1\x97\xd0\xbd\xd1\x81\xd1\x8c\xd0\xba\xd0\xb0',
           'fa_IR': 'Persian',
           'sv_SE': '\xd0\xa8\xd0\xb2\xd0\xb5\xd0\xb4\xd1\x81\xd1\x8c\xd0\xba\xd0\xb0',
           'he_IL': 'Hebrew',
           'T1': '\xd0\x92\xd0\xb8\xd0\xba\xd0\xbe\xd1\x80\xd0\xb8\xd1\x81\xd1\x82\xd0\xbe\xd0\xb2\xd1\x83\xd0\xb9\xd1\x82\xd0\xb5 \xd0\xba\xd0\xbd\xd0\xbe\xd0\xbf\xd0\xba\xd0\xb8 \xd0\x92\xd0\x92\xd0\x95\xd0\xa0\xd0\xa5 \xd1\x96 \xd0\x92\xd0\x9d\xd0\x98\xd0\x97, \xd1\x89\xd0\xbe\xd0\xb1 \xd0\xb2\xd0\xb8\xd0\xb1\xd1\x80\xd0\xb0\xd1\x82\xd0\xb8 \xd0\x92\xd0\xb0\xd1\x88\xd1\x83 \xd0\xbc\xd0\xbe\xd0\xb2\xd1\x83. \xd0\x9f\xd1\x96\xd1\x81\xd0\xbb\xd1\x8f \xd0\xb2\xd0\xb8\xd0\xb1\xd0\xbe\xd1\x80\xd1\x83 \xd0\xbd\xd0\xb0\xd1\x82\xd0\xb8\xd1\x81\xd0\xbd\xd1\x96\xd1\x82\xd1\x8c OK.',
           'T2': '\xd0\x92\xd0\xb8\xd0\xb1\xd1\x96\xd1\x80 \xd0\xbc\xd0\xbe\xd0\xb2\xd0\xb8'},
 'fy_x-FY': {'tr_TR': 'Turks',
             'fr_FR': 'Frans',
             'fi_FI': 'Finsk',
             'pt_PT': 'Portugeesk',
             'fy_x-FY': 'Frysk ',
             'it_IT': 'Italiaansk',
             'et_EE': 'Estonian',
             'no_NO': 'Noarsk',
             'nl_NL': 'Nederlansk',
             'lv_LV': 'Latvian',
             'el_GR': 'Gryks',
             'pt_BR_BR': 'Brazilian Portuguese',
             'hu_HU': 'Hongaarsk',
             'lt_LT': 'Lithuaniansk',
             'sl_SI': 'Slovenian',
             'hr_HR': 'Kroatysk',
             'en_EN': 'Engelsk',
             'es_ES': 'Spaans',
             'ca_AD': 'Catal\xc3\xa2nsk',
             'ru_RU': 'Russysk',
             'is_IS': 'Iislansk',
             'da_DK': 'Deensk',
             'ar_AE': 'Arabysk',
             'sk_SK': 'Slovakian',
             'de_DE': 'D\xc3\xbats',
             'sr_YU': 'Serbian',
             'cs_CZ': 'Tsjechysk',
             'pl_PL': 'Poolsk',
             'uk_UA': 'Oekra\xc3\xafne',
             'fa_IR': 'Persian',
             'sv_SE': 'Zweeds',
             'he_IL': 'Hebrew',
             'T1': 'Br\xc3\xbak de op en del toets om jo taal te kiezen. Dernei druk op OK',
             'T2': 'Taal Kieze'}}
